#pragma once

#include "math.h"

#define SMALL_NUMBER			(1.e-8f) // Copied from UE 5 MathModule

struct MatematikaCore
{
	inline static double Abs(double Value);
	inline static double Clamp(double Value, double Min, double Max);
	inline static double Min(double A, double B);
	inline static double Max(double A, double B);
	
	static double SumKorney(double x1, double x2);
	static double VozvestiVstepen(double n, int stepen);
	static long double LongFactorial(int n);
	static long int Factorial(int n);
	static void Diskriminant(int a, int b, int c);

	static double CalculateRad(double deg);
	static double CalculateDegFromRad(double rad);
	
	static double sin(double x);

	static void PoligonDlyaTestov();
	inline static double Sqrt(double Val) { return sqrt(Val); }; // vremenno ili postoyanno obertka nad C++ sqrt
public:
	static inline double Dist(double x1, double x2, double y1, double y2); // Auto generated by VC++ 6
	static inline double Sign(double Val); // Auto generated by VC++ 6
	static inline double Lerp(double Min, double Max, double Val); // Auto generated by VC++ 6
	static inline double ClampedLerp(double Min, double Max, double Val); // Auto generated by VC++ 6

	template< class T > 
	static T AbsT( const T A )
	{
		return (A >= (T)0) ? A : -A;
	}

	static inline bool IsNearlyEqual(float A, float B, float ErrorTolerance = SMALL_NUMBER)
	{
		return AbsT( A - B ) <= ErrorTolerance;
	}

	static inline bool IsNearlyEqual(double A, double B, double ErrorTolerance = SMALL_NUMBER)
	{
		return Abs(A - B) <= ErrorTolerance;
	}

	static inline bool IsNearlyZero(float Value, float ErrorTolerance = SMALL_NUMBER)
	{
		return Abs( Value ) <= ErrorTolerance;
	}

	static inline bool IsNearlyZero(double Value, double ErrorTolerance = SMALL_NUMBER)
	{
		return Abs( Value ) <= ErrorTolerance;
	}

	inline static double Floor(double Value)
	{
		return floor(Value);
	}

	inline static double Ceil(double Value)
	{
		return ceil(Value);
	}
};